
package com.soapconsumer.services;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "CoursePort", targetNamespace = "http://example.com/courses")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CoursePort {


    /**
     * 
     * @param getCourseDetailsRequest
     * @return
     *     returns com.soapconsumer.services.GetCourseDetailsResponse
     */
    @WebMethod(operationName = "GetCourseDetails")
    @WebResult(name = "GetCourseDetailsResponse", targetNamespace = "http://example.com/courses", partName = "GetCourseDetailsResponse")
    public GetCourseDetailsResponse getCourseDetails(
        @WebParam(name = "GetCourseDetailsRequest", targetNamespace = "http://example.com/courses", partName = "GetCourseDetailsRequest")
        GetCourseDetailsRequest getCourseDetailsRequest);

    /**
     * 
     * @param getAllCoursesDetailsRequest
     * @return
     *     returns com.soapconsumer.services.GetAllCoursesDetailsResponse
     */
    @WebMethod(operationName = "GetAllCoursesDetails")
    @WebResult(name = "GetAllCoursesDetailsResponse", targetNamespace = "http://example.com/courses", partName = "GetAllCoursesDetailsResponse")
    public GetAllCoursesDetailsResponse getAllCoursesDetails(
        @WebParam(name = "GetAllCoursesDetailsRequest", targetNamespace = "http://example.com/courses", partName = "GetAllCoursesDetailsRequest")
        GetAllCoursesDetailsRequest getAllCoursesDetailsRequest);

    /**
     * 
     * @param deleteCourseRequest
     * @return
     *     returns com.soapconsumer.services.DeleteCourseResponse
     */
    @WebMethod(operationName = "DeleteCourse")
    @WebResult(name = "DeleteCourseResponse", targetNamespace = "http://example.com/courses", partName = "DeleteCourseResponse")
    public DeleteCourseResponse deleteCourse(
        @WebParam(name = "DeleteCourseRequest", targetNamespace = "http://example.com/courses", partName = "DeleteCourseRequest")
        DeleteCourseRequest deleteCourseRequest);

}
