
package com.soapconsumer.services;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "CoursePortService", targetNamespace = "http://example.com/courses", wsdlLocation = "http://localhost:8080/ws/courses.wsdl")
public class CoursePortService
    extends Service
{

    private final static URL COURSEPORTSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.soapconsumer.services.CoursePortService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.soapconsumer.services.CoursePortService.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:8080/ws/courses.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8080/ws/courses.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        COURSEPORTSERVICE_WSDL_LOCATION = url;
    }

    public CoursePortService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CoursePortService() {
        super(COURSEPORTSERVICE_WSDL_LOCATION, new QName("http://example.com/courses", "CoursePortService"));
    }

    /**
     * 
     * @return
     *     returns CoursePort
     */
    @WebEndpoint(name = "CoursePortSoap11")
    public CoursePort getCoursePortSoap11() {
        return super.getPort(new QName("http://example.com/courses", "CoursePortSoap11"), CoursePort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CoursePort
     */
    @WebEndpoint(name = "CoursePortSoap11")
    public CoursePort getCoursePortSoap11(WebServiceFeature... features) {
        return super.getPort(new QName("http://example.com/courses", "CoursePortSoap11"), CoursePort.class, features);
    }

}
